# Generated by Django 4.2.3 on 2024-02-22 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_img', models.URLField()),
                ('url', models.URLField()),
                ('product_name', models.CharField(max_length=255)),
                ('seller_id', models.CharField(max_length=255)),
                ('product_price', models.PositiveIntegerField()),
                ('condition', models.CharField(max_length=255)),
                ('sell_status', models.CharField(max_length=255)),
                ('task_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Yahoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_type', models.CharField(default='bidorbuyprice', max_length=255)),
                ('price_min', models.PositiveIntegerField(default=2999)),
                ('price_max', models.PositiveIntegerField(default=30000)),
                ('condition_new', models.BooleanField(default=False)),
                ('condition_used', models.BooleanField(default=False)),
                ('condition_close_to_new', models.BooleanField(default=False)),
                ('condition_ok', models.BooleanField(default=False)),
                ('condition_soso', models.BooleanField(default=False)),
                ('condition_not_ok', models.BooleanField(default=False)),
                ('condition_bad', models.BooleanField(default=False)),
                ('order', models.CharField(default='新着順', max_length=255)),
                ('status', models.CharField(default='販売中', max_length=255)),
                ('abatch', models.CharField(default='', max_length=255)),
                ('option_delivery', models.BooleanField(default=False)),
                ('option_new', models.BooleanField(default=False)),
                ('option_end', models.BooleanField(default=False)),
                ('option_anon', models.BooleanField(default=False)),
                ('option_konbini', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Replace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before', models.CharField(max_length=255)),
                ('after', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replaces', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='タイトルなし', max_length=255)),
                ('num', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rakuma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_min', models.PositiveIntegerField(default=2999)),
                ('price_max', models.PositiveIntegerField(default=30000)),
                ('condition', models.CharField(default='new', max_length=255)),
                ('official_item_type', models.CharField(default='', max_length=255)),
                ('anonymous_shipping', models.BooleanField(default=False)),
                ('carriage', models.BooleanField(default=False)),
                ('transaction', models.CharField(default='selling', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paypay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_min', models.PositiveIntegerField(default=2999)),
                ('price_max', models.PositiveIntegerField(default=10000)),
                ('condition_new', models.BooleanField(default=False)),
                ('condition_close_to_new', models.BooleanField(default=False)),
                ('condition_ok', models.BooleanField(default=False)),
                ('condition_soso', models.BooleanField(default=False)),
                ('condition_not_ok', models.BooleanField(default=False)),
                ('order', models.CharField(default='openTime', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ngword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ngwords', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mercari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_min', models.PositiveIntegerField(default=2999)),
                ('price_max', models.PositiveIntegerField(default=40000)),
                ('condition_new', models.BooleanField(default=False)),
                ('condition_close_to_new', models.BooleanField(default=False)),
                ('condition_ok', models.BooleanField(default=False)),
                ('condition_soso', models.BooleanField(default=False)),
                ('condition_not_ok', models.BooleanField(default=False)),
                ('condition_bad', models.BooleanField(default=False)),
                ('order', models.CharField(default='おすすめ順', max_length=255)),
                ('on_sale', models.BooleanField(default=False)),
                ('sold_out', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Margin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.PositiveIntegerField(blank=True, null=True)),
                ('max_price', models.PositiveIntegerField(blank=True, null=True)),
                ('margin', models.PositiveIntegerField(blank=True, null=True)),
                ('row', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='margins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(default='', max_length=255)),
                ('row', models.PositiveIntegerField()),
                ('bool', models.BooleanField(default=False)),
                ('site', models.CharField(default='', max_length=10)),
                ('category_1', models.CharField(default='', max_length=255)),
                ('category_2', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('search_amount', models.PositiveIntegerField(default=50)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='scrape.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Exclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Delete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultMargin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bool', models.BooleanField(default=True)),
                ('margin', models.PositiveIntegerField(default=35)),
                ('delivery', models.PositiveIntegerField(default=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='margin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Common',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv', models.BooleanField(default=False)),
                ('get_info', models.BooleanField(default=False)),
                ('exclusion', models.BooleanField(default=False)),
                ('exclusion_size', models.PositiveIntegerField(default=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Amazon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.TextField(default='')),
                ('days_shipping', models.PositiveIntegerField(default=10)),
                ('point', models.PositiveIntegerField(default=2)),
                ('amount', models.PositiveIntegerField(default=2)),
                ('brand_name', models.CharField(default='ノーブランド品', max_length=255)),
                ('maker', models.CharField(default='ノーブランド品', max_length=255)),
                ('type_of_product', models.CharField(default='Hobbies', max_length=255)),
                ('contidion_of_product', models.CharField(default='新品', max_length=255)),
                ('browse_node', models.PositiveIntegerField(default=3113755051)),
                ('random_charactor', models.PositiveIntegerField(default=1)),
                ('prefix', models.CharField(default='', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='margin',
            constraint=models.UniqueConstraint(fields=('user', 'row'), name='margin_unique'),
        ),
        migrations.AddConstraint(
            model_name='keyword',
            constraint=models.UniqueConstraint(fields=('row', 'recipe'), name='keyword_unique'),
        ),
    ]
