# Generated by Django 4.2.3 on 2023-07-26 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="YahooSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_type",
                    models.CharField(default="bidorbuyprice", max_length=255),
                ),
                ("price_min", models.PositiveIntegerField(default=2999)),
                ("price_max", models.PositiveIntegerField(default=30000)),
                ("condition_new", models.BooleanField(default=False)),
                ("condition_used", models.BooleanField(default=False)),
                ("condition_close_to_new", models.BooleanField(default=False)),
                ("condition_ok", models.BooleanField(default=False)),
                ("condition_soso", models.BooleanField(default=False)),
                ("condition_not_ok", models.BooleanField(default=False)),
                ("condition_bad", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default="new")),
                ("status", models.CharField(default="販売中", max_length=255)),
                ("abatch", models.CharField(default="", max_length=255)),
                ("option_delivery", models.BooleanField(default=False)),
                ("option_new", models.BooleanField(default=False)),
                ("option_end", models.BooleanField(default=False)),
                ("option_anon", models.BooleanField(default=False)),
                ("option_konbini", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RakumaSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price_min", models.PositiveIntegerField(default=2999)),
                ("price_max", models.PositiveIntegerField(default=30000)),
                ("condition", models.CharField(default="new", max_length=255)),
                ("official_item_type", models.CharField(default="", max_length=255)),
                ("anonymous_shipping", models.BooleanField(default=False)),
                ("carriage", models.BooleanField(default=False)),
                ("transaction", models.CharField(default="selling", max_length=255)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PayPaySetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price_min", models.PositiveIntegerField(default=2999)),
                ("price_max", models.PositiveIntegerField(default=10000)),
                ("condition_new", models.BooleanField(default=False)),
                ("condition_close_to_new", models.BooleanField(default=False)),
                ("condition_ok", models.BooleanField(default=False)),
                ("condition_soso", models.BooleanField(default=False)),
                ("condition_not_ok", models.BooleanField(default=False)),
                ("order", models.CharField(default="openTime", max_length=255)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MercariSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price_min", models.PositiveIntegerField(default=2999)),
                ("price_max", models.PositiveIntegerField(default=40000)),
                ("condition_new", models.BooleanField(default=False)),
                ("condition_close_to_new", models.BooleanField(default=False)),
                ("condition_ok", models.BooleanField(default=False)),
                ("condition_soso", models.BooleanField(default=False)),
                ("condition_not_ok", models.BooleanField(default=False)),
                ("condition_bad", models.BooleanField(default=False)),
                ("order", models.CharField(default="0", max_length=255)),
                ("status", models.CharField(default="on_sale", max_length=255)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KeywordAndCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bool", models.BooleanField(default=False)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="scrape.recipe"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AmazonSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("condition", models.TextField(default="")),
                ("days_shipping", models.PositiveIntegerField(default=10)),
                ("point", models.PositiveIntegerField(default=2)),
                ("amount", models.PositiveIntegerField(default=2)),
                ("brand_name", models.CharField(default="ノーブランド", max_length=255)),
                ("maker", models.CharField(default="ノーブランド", max_length=255)),
                (
                    "type_of_product",
                    models.CharField(default="Hobbies", max_length=255),
                ),
                (
                    "contidion_of_product",
                    models.CharField(default="新品", max_length=255),
                ),
                ("browse_node", models.PositiveIntegerField(default=2189388051)),
                ("random_charactor", models.PositiveIntegerField(default=1)),
                ("prefix", models.CharField(default="", max_length=255)),
                (
                    "get_bool",
                    models.BooleanField(
                        default=False, verbose_name="リサーチ完了後、そのまま商品情報を取得する"
                    ),
                ),
                (
                    "csv_bool",
                    models.BooleanField(
                        default=False, verbose_name="第1キーワードを含まない商品を検索結果から除外する"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
