# Generated by Django 4.2.3 on 2023-07-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrape", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yahoosetting",
            name="order",
            field=models.CharField(default="new", max_length=255),
        ),
    ]
