# Generated by Django 4.2.3 on 2023-07-30 10:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("scrape", "0002_alter_yahoosetting_order"),
    ]

    operations = [
        migrations.RenameModel(old_name="AmazonSetting", new_name="Amazon",),
    ]
