# Generated by Django 4.2.3 on 2023-07-30 10:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("scrape", "0003_rename_amazonsetting_amazon"),
    ]

    operations = [
        migrations.RenameModel(old_name="KeywordAndCategory", new_name="Keyword",),
        migrations.RenameModel(old_name="MercariSetting", new_name="Mercari",),
        migrations.RenameModel(old_name="PayPaySetting", new_name="Paypay",),
        migrations.RenameModel(old_name="RakumaSetting", new_name="Rakuma",),
        migrations.RenameModel(old_name="YahooSetting", new_name="Yahoo",),
    ]
