# Generated by Django 4.2.3 on 2023-08-27 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scrape", "0004_rename_keywordandcategory_keyword_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="keyword",
            name="category_1",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="keyword",
            name="search_amount",
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name="keyword",
            name="site",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.CreateModel(
            name="SecondKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("second_keyword", models.CharField(default="", max_length=255)),
                (
                    "keyword",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="scrape.keyword"
                    ),
                ),
            ],
        ),
    ]
