# Generated by Django 4.2.3 on 2023-09-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrape", "0006_alter_keyword_recipe_alter_recipe_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="keyword",
            name="category_2",
            field=models.CharField(default="", max_length=255),
        ),
    ]
