# Generated by Django 4.2.3 on 2023-09-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrape", "0007_keyword_category_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="keyword",
            name="row",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
