# Generated by Django 4.2.3 on 2023-09-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrape", "0008_keyword_row"),
    ]

    operations = [
        migrations.AddField(
            model_name="keyword",
            name="keyword",
            field=models.CharField(default="", max_length=255),
        ),
    ]
