# Generated by Django 4.2.3 on 2023-09-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrape", "0010_keyword_second_keyword_1_keyword_second_keyword_2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keyword",
            name="second_keyword_1",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="keyword",
            name="second_keyword_2",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="keyword",
            name="second_keyword_3",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="keyword",
            name="second_keyword_4",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="keyword",
            name="second_keyword_5",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
