# Generated by Django 4.2.3 on 2023-10-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0013_remove_mercari_status_mercari_on_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='num',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(default='タイトルなし', max_length=255),
        ),
    ]
