# Generated by Django 4.2.3 on 2023-10-24 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrape', '0015_replace_ngword_exclusion_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delete',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exclusion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ngword',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ngwords', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='replace',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replaces', to=settings.AUTH_USER_MODEL),
        ),
    ]
