# Generated by Django 4.2.3 on 2023-10-27 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrape', '0016_alter_delete_user_alter_exclusion_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultMargin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margin', models.PositiveIntegerField(blank=True, null=True)),
                ('delivery', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Margin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.PositiveIntegerField(blank=True, null=True)),
                ('max_price', models.PositiveIntegerField(blank=True, null=True)),
                ('margin', models.PositiveIntegerField(blank=True, null=True)),
                ('row', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='margins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
