# Generated by Django 4.2.3 on 2023-11-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0018_defaultmargin_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='second_keyword_1',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='second_keyword_2',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='second_keyword_3',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='second_keyword_4',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='second_keyword_5',
        ),
        migrations.AlterField(
            model_name='mercari',
            name='order',
            field=models.CharField(default='おすすめ順', max_length=255),
        ),
    ]
