# Generated by Django 4.2.3 on 2023-11-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0019_remove_keyword_second_keyword_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_img1', models.URLField()),
                ('product_img2', models.URLField(blank=True, null=True)),
                ('product_img3', models.URLField(blank=True, null=True)),
                ('url', models.URLField()),
                ('product_name', models.CharField(max_length=255)),
                ('seller_id', models.CharField(max_length=30)),
                ('product_price', models.PositiveIntegerField()),
                ('task_id', models.CharField(max_length=30)),
            ],
        ),
    ]
