# Generated by Django 4.2.3 on 2023-11-08 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0020_researchresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchresult',
            name='seller_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='researchresult',
            name='task_id',
            field=models.CharField(max_length=255),
        ),
    ]
