# Generated by Django 4.2.3 on 2023-12-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0022_researchresult_condition_researchresult_sell_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazon',
            name='csv_bool',
        ),
        migrations.RemoveField(
            model_name='amazon',
            name='get_bool',
        ),
        migrations.AlterField(
            model_name='amazon',
            name='brand_name',
            field=models.CharField(default='ノーブランド品', max_length=255),
        ),
        migrations.AlterField(
            model_name='amazon',
            name='browse_node',
            field=models.PositiveIntegerField(default=3113755051),
        ),
        migrations.AlterField(
            model_name='amazon',
            name='maker',
            field=models.CharField(default='ノーブランド品', max_length=255),
        ),
    ]
