# Generated by Django 4.2.3 on 2023-12-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0023_remove_amazon_csv_bool_remove_amazon_get_bool_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultmargin',
            name='bool',
            field=models.BooleanField(default=True),
        ),
    ]
