# Generated by Django 4.2.3 on 2023-12-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0024_defaultmargin_bool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultmargin',
            name='delivery',
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='defaultmargin',
            name='margin',
            field=models.PositiveIntegerField(default=35),
        ),
    ]
