# Generated by Django 4.2.3 on 2023-12-15 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0025_alter_defaultmargin_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='category_2',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
