# Generated by Django 4.2.3 on 2023-12-19 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0026_alter_keyword_category_2'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='delete',
            constraint=models.UniqueConstraint(fields=('user', 'row'), name='delete_unique'),
        ),
        migrations.AddConstraint(
            model_name='exclusion',
            constraint=models.UniqueConstraint(fields=('user', 'row'), name='exclusion_unique'),
        ),
        migrations.AddConstraint(
            model_name='keyword',
            constraint=models.UniqueConstraint(fields=('row', 'keyword'), name='keyword_unique'),
        ),
        migrations.AddConstraint(
            model_name='margin',
            constraint=models.UniqueConstraint(fields=('user', 'row'), name='margin_unique'),
        ),
        migrations.AddConstraint(
            model_name='ngword',
            constraint=models.UniqueConstraint(fields=('user', 'row'), name='ngword_unique'),
        ),
        migrations.AddConstraint(
            model_name='replace',
            constraint=models.UniqueConstraint(fields=('user', 'row'), name='replace_unique'),
        ),
    ]
