# Generated by Django 4.2.3 on 2023-12-19 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0027_delete_delete_unique_exclusion_exclusion_unique_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='keyword',
            name='keyword_unique',
        ),
        migrations.AddConstraint(
            model_name='keyword',
            constraint=models.UniqueConstraint(fields=('row', 'recipe'), name='keyword_unique'),
        ),
    ]
