# Generated by Django 4.2.3 on 2024-01-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0028_remove_keyword_keyword_unique_keyword_keyword_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yahoo',
            name='order',
            field=models.CharField(default='新着順', max_length=255),
        ),
    ]
