# Generated by Django 4.2.3 on 2024-01-12 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0029_alter_yahoo_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researchresult',
            old_name='product_img1',
            new_name='product_img',
        ),
        migrations.RemoveField(
            model_name='researchresult',
            name='product_img2',
        ),
        migrations.RemoveField(
            model_name='researchresult',
            name='product_img3',
        ),
    ]
