# Generated by Django 4.2.3 on 2024-01-17 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0030_rename_product_img1_researchresult_product_img_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='delete',
            name='delete_unique',
        ),
        migrations.RemoveConstraint(
            model_name='exclusion',
            name='exclusion_unique',
        ),
        migrations.RemoveConstraint(
            model_name='ngword',
            name='ngword_unique',
        ),
        migrations.RemoveConstraint(
            model_name='replace',
            name='replace_unique',
        ),
        migrations.RemoveField(
            model_name='delete',
            name='row',
        ),
        migrations.RemoveField(
            model_name='exclusion',
            name='row',
        ),
        migrations.RemoveField(
            model_name='ngword',
            name='row',
        ),
        migrations.RemoveField(
            model_name='replace',
            name='row',
        ),
    ]
